In [15]:
#we will learn to load pkl files and models 
# how we can convert new data in raw format to our desired format

import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import numpy as np
import pandas as pd

In [16]:
## load trained model,scaler ppickle, and onehot encoded files
model=load_model('model.h5')

In [17]:
## loading the encoder and scaler
with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender=pickle.load(file)

with open ('onehot_encoder_geo.pkl','rb') as file:
    onehot_encoder_geo=pickle.load(file)

with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)

In [18]:
##Example input
input_data={
    'CreditScore':608.00,
    'Geography':'Germany',
    'Gender':'Male',
    'Age':41.00,
    'Tenure':1.00,
    'Balance':83807.86,
    'NumOfProducts':1.00,
    'HasCrCard':0.00,
    'IsActiveMember':1.00,
    'EstimatedSalary':112542.58,
}

In [19]:
#one hot encode Geography
geo_encoded=label_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=label_encoder_geo.get_feature_names_out(['Geography']))

d:\Coding Stuff\venv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [20]:
## converting input_data from key value pairs to dataframe
input_df=pd.DataFrame([input_data])

In [21]:
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,608.0,Germany,Male,41.0,1.0,83807.86,1.0,0.0,1.0,112542.58

In [22]:
## encode categorical variables
input_df['Gender']=label_encoder_gender.transform(input_df['Gender'])

In [23]:
## concatination onehot encoded
input_df=pd.concat([input_df.drop("Geography",axis=1),geo_encoded_df],axis=1)

In [24]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,608.0,1,41.0,1.0,83807.86,1.0,0.0,1.0,112542.58,0.0,1.0,0.0

In [25]:
## scaling the input data
input_scaled=scaler.transform(input_df)

In [26]:
##Predicting churn
prediction=model.predict(input_scaled)
prediction_proba=prediction[0][0]
prediction_proba

1/1 [==============================] - 0s 36ms/step

0.380491

In [27]:
prediction

array([[0.380491]], dtype=float32)

In [28]:
if prediction_proba>0.5:
    print('The customer is likely to churn')
else:
    print('The customer is not likely to churn')

The customer is not likely to churn